.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

===========
/admin/cron
===========

.. contents::


Methods
*******

GET
+++

List cron jobs.

Example: ::

  < GET /admin/cron

  > 200 Ok
  >
  > [
  >   {
  >     uri: "/admin/cron/process_queues"
  >   , frequency: 1
  >   , since: "2008-08-04T11:51:00Z"
  >   , enabled: true
  >   }
  > , {
  >     uri: "/admin/cron/cleanup_shared_tmp"
  >   , frequency: 86400
  >   , since: "2013-05-01T03:15:00Z"
  >   , enabled: true
  >   }
  > , ...
  > ]

POST
++++

Process cron jobs.

Example: ::

  < POST /admin/cron
  < Content-Type: $CT:cron-poke
  <
  < ...

  > 202 Accepted

