.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

====================
/admin/readonly-mode
====================

.. contents::


Methods
*******

GET
+++

Example: ::

  < GET /admin/readonly-mode
  < Accept: $CT:readonly-mode

  > 200 Ok
  > Content-Type: $CT:readonly-mode
  >
  > {
  >   instance: "https://example.com/"
  > , readonly: true
  > }

PUT
+++

Example: ::

  < PUT /admin/readonly-mode
  < Content-Type: $CT:readonly-mode
  < Prefer: return=minimal
  <
  < {
  <   instance: "https://example.com/"
  < , readonly: false
  < }

  > 204 No Content

