.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

=========================
/appliances/:app/:version
=========================

.. contents::


Media Types
***********

See `Media Types`_.

.. _`Media Types`: media-types.rest


Methods
*******

DELETE
++++++

Delete an appliance version.

This removes all images of the given appliance version.

Spec: ::

  Status:
    204 No Content
  | 409 Conflict
  | 412 Precondition Failed

Example: ::

  < DELETE /appliance/123

  > 204 No Content

Example: ::

  < DELETE /appliance/123

  > 409 Conflict
  >
  > {
  >   error: {
  >     code: "appliance_is_published"
  >   }
  > }

GET
+++

Describe given version of an appliance.

Example: ::

  < GET /appliances/123/4.5.6

  > 200 Ok
  >
  > {
  >   name: "My New Appliance"
  >   icon: "/theme/logo/thumbnail/02d3230a1e4c9773cc12fau74982a16d2"
  >   arch: "x86_64"
  >   ...
  > }

