.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

================
/appliances/:app
================

.. contents::


Media Types
***********

See `Media Types`_.

.. _`Media Types`: ../../media-types.rest


Methods
*******

DELETE
++++++

Delete an appliance.

Spec: ::

  Accept:
    $CT:appliance-result
  Prefer:
    return=minimal

  Status:
    200 Ok
  | 204 No Content
  | 409 Conflict
  Content-Type:
    &Accept

Example: ::

  < DELETE /appliance/123
  < Accept: $CT:appliance-result

  > 200 Ok
  > Content-Type: $CT:appliance-result
  >
  > ...

Example: ::

  < DELETE /appliance/123
  < Prefer: return=minimal

  > 204 No Content

GET
+++

Describe the latest version of an appliance.

Spec: ::

  Accept:
    $CT:appliance-description

  Content-Type:
    &Accept

Example: ::

  < GET /appliances/123
  < Accept: $CT:appliance-description

  > 200 Ok
  > Content-Type: $CT:appliance-description
  >
  > ...

