.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

==================================
SUSE Studio APIv3 design documents
==================================

* Overview_ discusses design guidelines for SUSE Studio APIv3.
* REST_ describes the architectural style in the context of HTTP.
* `HTTP Status Codes`_ discusses semantics of HTTP status codes
  and their use in SUSE Studio APIv3.
* Resources_ describes exposed resources and semantics of their
  manipulation.
* `schema/`_ contains proposed JSON Schema v04 descriptions,
  using CoffeeScript_ syntax.
* `Server`_ documents currently preferred tooling for the server-side
  implementation.
* Feedback_ sums up the discussions I've had with APIv2 users
  about its shortcomings and APIv3 directions.

Everything here is very much WIP.

.. _Overview: overview.rest
.. _REST:     REST.rest
.. _HTTP Status Codes: http-status.rest
.. _Resources: resources.rest
.. _schema/:  ./schema/
.. _CoffeeScript: http://coffeescript.org/
.. _Feedback: feedback.rest
.. _Server: server.rest
