.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

==================================
SUSE Studio APIv3 design documents
==================================

* Overview_ discusses design guidelines for SUSE Studio APIv3.
* `HTTP Status Codes`_ discusses semantics of HTTP status codes
  and their use in SUSE Studio APIv3.
* REST_ describes the architectural style in the context of HTTP.
* `schema/`_ contains proposed JSON Schema v04 descriptions,
  using CoffeeScript_ syntax.
* Feedback_ sums up the discussions I've had with APIv2 users
  about its shortcomings and APIv3 directions.

Everything here is very much WIP.

.. _Overview: overview.rest
.. _HTTP Status Codes: http-status.rest
.. _REST:     REST.rest
.. _schema/:  ./schema/
.. _CoffeeScript: http://coffeescript.org/
.. _Feedback: feedback.rest
