.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

=======================
User-oriented resources
=======================

.. contents::

Common
******

This document uses the following "macros" to reduce the chattiness,
as well as the churn induced by involving this proposal.

$CT:appliances
  application/vnd.suse.studio.appliances.v3+json
$CT:appliance-clone-request
  application/vnd.suse.studio.appliance-clone-request.v3+json
$CT:appliance-config
  application/vnd.suse.studio.appliance-configuration.v3+json
$CT:appliance-config-patch
  application/vnd.suse.studio.appliance-configuration-patch.v3+json
$CT:appliance-status
  application/vnd.suse.studio.appliance-status.v3+json
$CT:build-request
  application/vnd.suse.studio.build-request.v3+json
$CT:build-status
  application/vnd.suse.studio.build-status.v3+json
$CT:repositories
  application/vnd.suse.studio.repositories.v3+json
$CT:result
  application/vnd.suse.studio.result.v3+json
$CT:testdrive
  application/vnd.suse.studio.testdrive.v3+json

Appliances
**********

**GET /appliances**

List my appliances.

Spec: ::

  Accept:
    $CT:appliances

Example: ::

  < GET /appliances
  < Accept: $CT:appliances

  > 200 Ok
  > Content-Type: $CT:appliances
  >
  > ...

**POST /appliances**

Create an appliance.

Spec: ::

  Content-Type:
    $CT:appliance-config
  | $CT:appliance-clone-request
  Accept:
    $CT:appliance-config
  | $CT:appliance-status
  | $CT:result
  Prefer:
    return=minimal

  Location:
    $URI

Example: ::

  < POST /appliances
  < Content-Type: $CT:appliance-clone-request
  < Accept: $CT:appliance-config
  <
  < ...

  > 201 Created
  > Location: /appliances/123
  > Content-Type: $CT:appliance-config
  >
  > ...

  < POST /appliances
  < Content-Type: $CT:appliance-clone-request
  < Accept: $CT:appliance-result

  > 201 Created
  > Location: /appliances/123
  > Content-Type: $CT:appliance-result
  >
  > ...

Appliance
*********

**DELETE /appliances/:app**

Delete an appliance.

Spec: ::

  Accept:
    $CT:appliance-result
  Prefer:
    return=minimal

  Status:
    200 Ok
  | 204 No Content
  | 409 Conflict

Example: ::

  < DELETE /appliance/123
  < Accept: $CT:appliance-result

  > 200 Ok
  > Content-Type: $CT:appliance-result
  >
  > ...

Example: ::

  < DELETE /appliance/123
  < Prefer: return=minimal

  > 204 No Content

**GET /appliances/:app**

Describe the latest version of an appliance.

Spec: ::

  Accept:
    $CT:appliance-config
  | $CT:appliance-status

  Content-Type:
    &Accept

Example: ::

  < GET /appliances/123
  < Accept: $CT:appliance-config

  > 200 Ok
  > Content-Type: $CT:appliance-config
  >
  > ...

**PATCH /appliances/:app**

Modify the configuration of an appliance.

Spec: ::

  Content-Type:
    $CT:appliance-config-patch
  Accept:
    $CT:appliance-config
  | $CT:appliance-status
  Prefer:
    return=minimal

  Status:
    200 Ok
  | 204 No Content
  | 409 Conflict
  | 412 Precondition Failed
  Content-Type:
    &Accept

Example: ::

  < PATCH /appliances/123
  < Content-Type: $CT:appliance-config-patch
  < Accept: $CT:appliance-config

  > 200 Ok
  > Content-Type: $CT:appliance-config
  >
  > ...

Example: ::

  < PATCH /appliances/123
  < Content-Type: $CT:appliance-config-patch
  < Prefer: return=minimal

  > 204 No Content

Appliance Version
*****************

**DELETE /appliances/:app/:version**

Delete an appliance version.

This removes all images of the given appliance version.

Spec: ::

  Accept:
    $CT:result
  Prefer:
    return=minimal

  Status:
    200 Ok
  | 204 No Content
  | 409 Conflict
  | 412 Precondition Failed
  Content-Type:
    &Accept

Example: ::

  < DELETE /appliance/123
  < Accept: $CT:result

  > 200 Ok
  > Content-Type: $CT:result
  >
  > ...

Example: ::

  < DELETE /appliance/123
  < Prefer: return=minimal

  > 204 No Content


**GET /appliances/:app/:version**

Describe given version of an appliance.

Spec: ::

  Accept:
    $CT:appliance-config
  | $CT:appliance-status

  Status:
    200 Ok
  | 412 Precondition Failed
  Content-Type:
    &Accept


Appliance Builds
****************

**DELETE /appliances/:app/:version/:format**

Delete the built `:format` image of the `:version` of `:app`.

Spec: ::

  Accept:
    $CT:result

  Status:
    200 Ok
  | 409 Conflict
  | 412 Precondition Failed
  Content-Type:
    &Accept


**GET /appliances/:app/:version/:format**

Fetch the built `:format` image of the `:version` of `:app`.

Spec: ::

  Accept: 
    application/x-bzip-compressed-tar     ; tar.bz tar.bz2 tbz tbz2
  | application/x-compressed-tar          ; tar.gz tar.Z tgz taz
  | application/zip                       ; zip

  Status:
    200 Ok
  | 406 Not Acceptable
  Content-Type:
    &Accept
  Content-Disposition:
    FILENAME

**POST /appliances/:app**

Build images for the current (or given) version of the appliance.

Spec: ::

  Accept:
    $CT:build-status
  Content-Type:
    $CT:build-request

  Status:
    200 Ok
  | 201 Created
  Content-Type:
    &Accept
  Location:
    /appliances/:app/:version
    /appliances/:app/:version/:format

Example: ::

  < POST /appliances/123
  < Content-Type: $CT:build-request
  < Accept: $CT:build-status
  <
  < ...

  > 201 Created
  > Location: /appliances/123/4.5.6
  < Content-Type: $CT:build-status

Repositories
************

**GET /repositories**

List repositories.

Spec: ::

  Accept:
    $CT:repositories

Example: ::

  < GET /repositories
  < Accept: $CT:repositories

  > 200 Ok
  > Content-Type: $CT:repositories
  >
  > ...

**POST /repositories**

Import one or more repositories.


Repository
**********

**DELETE /repositories/:name**

Remove a repository.


**GET /repositories/:name**

Fetch information about a repository.


**PUT /repositories/:name**

Import a repository, possibly overwriting.


**POST /repositories/:name/refresh**

Update package metadata for a repository.


Appliance Repositories
**********************

**GET /appliances/:app/repositories**

List repositories used for the appliance.


**POST /appliances/:app/repositories**

Add a repository into the appliance.


Appliance Repository
********************

**DELETE /appliances/:app/repositories/:name**

Delete a repository from the appliance.


Appliance Software
******************

Selected
++++++++

**GET /software/:app/selected**

List packages and patterns included in the appliance.


**PATCH /software/:app/selected**

Modify the list packages and patterns included in the appliance.


**POST /software/:app/selected**

Add packages and patterns included in the appliance.


**PUT /software/:app/selected**

Set packages and patterns included in the appliance.


Banned
++++++

**GET /software/:app/banned**

List packages banned from the appliance.


**PATCH /software/:app/banned**

Modify the list packages and patterns included in the appliance.


**POST /software/:app/banned**

Add packages banned from the appliance.


**PUT /software/:app/banned**

Set packages banned from the appliance.


Overlay Files
*************

WIP

GPG Keys
********

WIP


Testdrives
**********

**POST /appliances/:app/:version/:format**

Spec: ::

  Content-Type:
    $CT:testdrive
  Accept:
    &Content-Type

  Status:
    202 Accepted
  Content-Type:
    &Accept
  Location:
    /testdrives/:token                     ; /testdrives/sNa6Fu9BaR

**DELETE /testdrives/:token**

Spec: ::

  Accept:
    $CT:result

  Status:
    200 Ok
  | 204 No Content
  Content-Type:
    &Accept

GET /testdrives/sNa6Fu9BaR

Spec: ::

  Accept:
    $CT:testdrive

  Status:
    200 Ok
  Content-Type:
    &Accept

