.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

========================
Admin-oriented resources
========================

.. contents::

Common
******

This document uses the following "macros" to reduce the chattiness,
as well as the churn induced by involving this proposal.

$CT:readonly-mode
  application/vnd.suse.studio.readonly-mode.v3+json


Read-only Mode
**************

**GET /admin/readonly-mode**

Example: ::

  < GET /admin/readonly-mode
  < Accept: $CT:readonly-mode

  > 200 Ok
  > Content-Type: $CT:readonly-mode
  >
  > {
  >   instance: "https://example.com/"
  > , readonly: true
  > }

**PUT /admin/readonly-mode**

Example: ::

  < PUT /admin/readonly-mode
  < Content-Type: $CT:readonly-mode
  < Prefer: return=minimal
  <
  < {
  <   instance: "https://example.com/"
  < , readonly: false
  < }

  > 204 No Content


Runners
*******

**GET /runners**

List runners.

Example: ::

  < GET /runners
  < Accept: $CT:runners

  > 200 Ok
  > Content-Type: $CT:runners
  >
  > {
  >   "a.runners.susestudio.com": {
  >     "host": "a.runners.susestudio.com"
  >   , "port": 3005
  >   , "state": "active"
  >   , "preferred": true
  >   , "avg-load": "0.5"
  >   , "arch": "x86_64"
  >   , "last-pinged": "2013-04-05T11:44:59Z"
  >   , "capacity": {
  >       "kiwi": 2
  >     , "testdrive": 2
  >     , "amazon": 0
  >     , "azure": 0
  >     }
  >   , "running": {
  >       "kiwi": 1
  >     , "testdrive": 2
  >     , "amazon": 0
  >     , "azure": 0
  >     }
  >   }
  > , "b.runners.susestudio.com": {
  >     "host": "b.runners.susestudio.com"
  >   , "port": 3005
  >   , "state": "disabled"
  >   , "preferred": false
  >     ...
  >   }
  > }

**PATCH /runners**

Example: ::

  < PATCH /runners/a.runners.susestudio.com
  < Accept: $CT:runner
  < Content-Type: $CT:runners-change
  <
  < [
  <   { "op": "replace"
  <   , "path": "/a.runners.susestudio.com/state"
  <   , "value": "disabled"
  <   }
  < , { "op": "replace"
  <   , "path": "/a.runners.susestudio.com/preferred"
  <   , "value": false
  <   }
  < , { "op": "replace"
  <   , "path": "/b.runners.susestudio.com/state"
  <   , "value": "active"
  <   }
  < , { "op": "replace"
  <   , "path": "/b.runners.susestudio.com/preferred"
  <   , "value": true
  <   }
  < ]

  > 200 Ok
  > Content-Type: $CT:runner
  >
  > {
  >   "a.runners.susestudio.com": {
  >     "host": "a.runners.susestudio.com"
  >   , "port": 3005
  >   , "state": "disabled"
  >   , "preferred": false
  >     ...
  >   }
  > , "b.runners.susestudio.com": {
  >     "host": "b.runners.susestudio.com"
  >   , "port": 3005
  >   , "state": "active"
  >   , "preferred": true
  >     ...
  >   }
  > }



Runner
******

**DELETE /runners/:hostname**

Drop a runner.

Example: ::

  < DELETE /runners/b.runners.susestudio.com
  < Accept: $CT:runners

  > 204 Ok
  > Content-Type: $CT:runners
  > Content-Location: /runners
  >
  > {
  >   "a.runners.susestudio.com": { ... }
  > , "c.runners.susestudio.com": { ... }
  > }

**GET /runners/:hostname**

Retrieve information about a runner.

Example: ::

  < GET /runners/a.runners.susestudio.com
  < Accept: $CT:runner

  > 200 Ok
  > Content-Type: $CT:runner
  >
  > {
  >   "host": "a.runners.susestudio.com"
  > , "port": 3005
  > , "state": "active"
  > , "preferred": true
  > , "avg-load": "0.5"
  > , "arch": "x86_64"
  > , "last-pinged": "2013-04-05T11:44:59Z"
  >   ...
  > }

**PATCH /runners/:hostname**

Example: ::

  < PATCH /runners/a.runners.susestudio.com
  < Accept: $CT:runner
  < Content-Type: $CT:runner-change
  <
  < [
  <   { "op": "replace", "path": "/state", "value": "disabled" }
  <   { "op": "replace", "path": "/preferred", "value": false }
  <   { "op": "replace", "path": "/capacity/kiwi", "value": 1 }
  < ]

  > 200 Ok
  > Content-Type: $CT:runner
  >
  > {
  >   "host": "a.runners.susestudio.com"
  > , "port": 3005
  > , "state": "disabled"
  > , "preferred": false
  > , "avg-load": "0.5"
  > , "arch": "x86_64"
  > , "last-pinged": "2013-04-05T11:44:59Z"
  >   ...
  > }


**PUT /runners/:hostname**

Create or update a runner.

Example: ::

  < PUT /runners/c.runners.susestudio.com
  < Accept: $CT:runner
  < Content-Type: $CT:runner
  <
  < {
  <   "host": "c.runners.susestudio.com"
  < , "port": 3005
  < , "state": "active"
  < , "preferred": false
  < , "capacity": {
  <     "kiwi": 1
  <   , "testdrive": 2
  <   , "amazon": 0
  <   , "azure": 0
  <   }
  < , "running": {
  <     "kiwi": 1
  <   , "testdrive": 2
  <   , "amazon": 0
  <   , "azure": 0
  <   }
  < }

  > 200 Ok
  > Content-Type: $CT:runner
  >
  > {
  >   "host": "c.runners.susestudio.com"
  > , "port": 3005
  > , "state": "active"
  > , "preferred": false
  > , "avg-load": "0.1"
  > , "arch": "x86_64"
  > , "last-pinged": "2013-04-05T13:16:21Z"
  >   ...
  > }



Builds
******

**GET /builds/running**

List running builds.

**GET /builds/queued**

List queued builds.


Uploads to Amazon
*****************

**GET /amazons/running**

List running uploads.

**GET /amazons/queued**

List queued uploads.


Uploads to Azure
****************

**GET /azures/running**

List running uploads.

**GET /azures/queued**

List queued uploads.


Cron Jobs
*********

**GET /cron**

List cron jobs.

**POST /cron**

Process cron jobs.


Cron Job
********

**DELETE /cron/:job**

Drop a cron job.

**GET /cron/:job**

Show info on a cron job.

**POST /cron/:job**

Run a cron job.

**PUT /cron/:job**

Create a cron job.


Base Repositories
*****************

**GET /base-repositories**

List base repositories.

**POST /base-repositories**

Enable or disable base repositories.


Appliance Templates
*******************

**GET /base-systems**

List base systems.

**POST /base-systems**

Enable or disable base systems.

