.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

=======================
User-oriented resources
=======================


* `/appliances`_
* `/appliances/:app`_
* `/appliances/:app/:version`_
* `/appliances/:app/:version/:format`_
* `/appliances/:app/:version/configuration`_
* `/appliances/:app/configuration`_
* `/appliances/:app/files/data/:path`_
* `/appliances/:app/files/info/:path`_
* `/appliances/:app/gpg_keys`_
* `/appliances/:app/gpg_keys/:key`_
* `/appliances/:app/repositories`_
* `/appliances/:app/repositories/:name`_
* `/appliances/:app/status`_
* `/builds/queued`_
* `/builds/running`_
* `/gallery`_
* `/gallery/:app`_
* `/gallery/:app/:version`_
* `/gallery/:app/comments`_
* `/gallery/:app/rating`_
* `/packages`_
* `/packages/:pkg`_
* `/repositories`_
* `/repositories/:name`_
* `/repositories/:name/refresh`_
* `/software/:app/banned`_
* `/software/:app/selected`_
* `/templates`_
* `/testdrives`_
* `/testdrives/:token`_

[Top_]

.. _`/appliances`:              resources/appliances.rest
.. _`/appliances/:app`:         resources/appliances/:app.rest
.. _`/appliances/:app/:version`:
    resources/appliances/:app/:version.rest
.. _`/appliances/:app/:version/:format`:
    resources/appliances/:app/:version/:format.rest
.. _`/appliances/:app/:version/configuration`:
    resources/appliances/:app/:version/configuration.rest
.. _`/appliances/:app/configuration`:
    resources/appliances/:app/configuration.rest
.. _`/appliances/:app/files/data/:path`:
    resources/appliances/:app/files/data/:path.rest
.. _`/appliances/:app/files/info/:path`:
    resources/appliances/:app/files/info/:path.rest
.. _`/appliances/:app/gpg_keys`:
    resources/appliances/:app/gpg_keys.rest
.. _`/appliances/:app/gpg_keys/:key`:
    resources/appliances/:app/gpg_keys/:key.rest
.. _`/appliances/:app/repositories`:
    resources/appliances/:app/repositories.rest
.. _`/appliances/:app/repositories/:name`:
    resources/appliances/:app/repositories/:name.rest
.. _`/appliances/:app/status`:
    resources/appliances/:app/status.rest
.. _`/builds/queued`:           resources/builds/queued.rest
.. _`/builds/running`:          resources/builds/running.rest
.. _`/gallery`:                 resources/gallery.rest
.. _`/gallery/:app`:            resources/gallery/:app.rest
.. _`/gallery/:app/:version`:   resources/gallery/:app/:version.rest
.. _`/gallery/:app/comments`:   resources/gallery/:app/comments.rest
.. _`/gallery/:app/rating`:     resources/gallery/:app/rating.rest
.. _`/packages`:                resources/packages.rest
.. _`/packages/:pkg`:           resources/packages/:pkg.rest
.. _`/repositories`:            resources/repositories.rest
.. _`/repositories/:name`:      resources/repositories/:name.rest
.. _`/repositories/:name/refresh`:
    resources/repositories/:name/refresh.rest
.. _`/software/:app/banned`:    resources/software/:app/banned.rest
.. _`/software/:app/selected`:  resources/software/:app/selected.rest
.. _`/templates`:               resources/templates.rest
.. _`/testdrives`:              resources/testdrives.rest
.. _`/testdrives/:token`:       resources/testdrives/:token.rest

.. _Top: README.rest
