.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

===========================
/repositories/:name/refresh
===========================

.. contents::


Media Types
***********

See `Media Types`_.

.. _`Media Types`: media-types.rest


Methods
*******

POST
++++

Update package metadata for a repository.

