.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

===========
/appliances
===========

.. contents::


Media Types
***********

See `Media Types`_.

.. _`Media Types`: media-types.rest


Methods
*******

GET
+++

List my appliances.

Example: ::

  < GET /appliances

  > 200 Ok
  >
  > [
  >   {
  >     uri: "/appliances/123"
  >   , name: "..."
  >   , icon: "/theme/logos/..."
  >   , gallery: "/gallery/123"
  >   , arch: "x86_64"
  >   , software: {
  >       patterns: 3
  >     , packages: 157
  >     , repositories: [
  >         {
  >           uri: "/repositories/..."
  >         , name: "openSUSE-12.3-oss"
  >         , truested: true
  >         }
  >       , {
  >           uri: "/repositories/..."
  >         , name: "openSUSE-12.3-updates"
  >         , truested: true
  >         }
  >       ]
  >     }
  >   }
  > , {
  >     uri: "/appliances/169"
  >   }
  > ]

POST
++++

Create an appliance.

Example: ::

  < POST /appliances
  <
  < {
  <   source: "/appliances/1"
  < , name: "My New Appliance"
  < , arch: "x86_64"
  < }

  > 201 Created
  > Content-Location: /appliances/123
  >
  > ... see GET /appliances/:app

  < POST /appliances
  <
  < {
  <   based_on: "12.3"
  < , arch: "x86_64"
  < , name: "Imported Appliance"
  < , config: "<?xml ..."
  < }

  > 201 Created
  > Content-Location: /appliances/123
  >
  > ... see GET /appliances/:app

