.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

==================
/base-repositories
==================

.. contents::


Methods
*******

GET
+++

List base repositories.

POST
++++

Enable or disable base repositories.

