.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

=============
/base-systems
=============

.. contents::


Methods
*******


GET
+++

List base systems.

POST
++++

Enable or disable base systems.

