.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

=====
/cron
=====

.. contents::


Media Types
***********

See `Media Types`_.

.. _`Media Types`: media-types.rest


Methods
*******

GET
+++

List cron jobs.

POST
++++

Process cron jobs.

