.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

=========
/packages
=========

.. contents::


Methods
*******

GET
+++

List custom packages for all base systems.

Example: ::

  < GET /packages

  > 200 Ok
  >
  > [
  >   {
  >     uri: "/packages/12.3/private-code-1.2.rpm"
  >   , download: "/packages/12.3/private-code-1.2.rpm/data"
  >   , file: "private-code-1.2.rpm"
  >   , size: 587500
  >   , arch: "x86_64"
  >   }
  > , {
  >     uri: "/packages/12.2/libcustom-2.12.x86_64.rpm"
  >   , download: "/packages/12.3/libcustom-2.12.x86_64.rpm/data"
  >   , file: "libcustom-2.12.x86_64.rpm"
  >   , size: 3267345
  >   , arch: "x86_64"
  >   }
  > ]

