.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

=====================
/software/:app/banned
=====================

.. contents::


Methods
*******

GET
+++

List packages banned from the appliance.

Example: ::

  < GET /software/123/banned

  > 200 Ok
  >
  > [
  >   "gnome"
  > , "kde4"
  > ]

PATCH
+++++

Modify the list packages and patterns included in the appliance.

Example: ::

  < PATCH /software/123/banned
  <
  < [
  <   { "op": "add", "path": "/-", "value": "e17" }
  < ]

  > 200 Ok
  >
  > [
  >   "e17"
  > , "gnome"
  > , "kde4"
  > ]

PUT
+++

Set packages banned from the appliance.

Example: ::

  < PUT /software/123/banned
  <
  < [
  <   "gnome"
  < , "kde4"
  < ]

  > 200 Ok
  >
  > [
  >   "gnome"
  > , "kde4"
  > ]

