.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

==============
/builds/queued
==============

.. contents::


Media Types
***********

See `Media Types`_.

.. _`Media Types`: ../../media-types.rest


Methods
*******

GET
+++

List queued builds.

Example: ::

  < GET /builds/queued

  > 200 Ok
  > Content-Type: $CT:builds-queued
  >
  > {
  >   {
  >     "appliance": "/appliances/123"
  >   , "format": "iso"
  >   , "queued": "2013-04-16T11:23:45Z"
  >   }
  > , {
  >     "appliance": "/appliances/123"
  >   , "format": "xen"
  >   , "queued": "2013-04-16T11:23:45Z"
  >   }
  > }

POST
++++

Queue a build or KIWI export.

Spec: ::

  Accept:
    $CT:builds-queued
  Content-Type:
    $CT:build-request

  Status:
    200 Ok
  Content-Type:
    &Accept
  Content-Location:
    /builds/queued

Example: ::

  < POST /builds/queued
  <
  < {
  <   "appliance": "/appliances/123"
  < , "format": "oem"
  < , "type": "image"
  < }

  > 200 Ok
  >
  > {
  >   {
  >     "appliance": "/appliances/123"
  >   , "format": "iso"
  >   , "type": "image"
  >   , "queued": "2013-04-16T11:23:45Z"
  >   }
  > , {
  >     "appliance": "/appliances/123"
  >   , "format": "xen"
  >   , "type": "image"
  >   , "queued": "2013-04-16T11:23:45Z"
  >   }
  > , {
  >     "appliance": "/appliances/123"
  >   , "format": "oem"
  >   , "type": "kiwi"
  >   , "queued": "2013-04-17T09:11:23Z"
  >   }
  > }

  < POST /builds/queued
  <
  < {
  <   "appliance": "/appliances/123"
  < , "format": "vmx"
  < , "type": "kiwi"
  < }

  > 200 Ok
  >
  > {
  >   {
  >     "appliance": "/appliances/123"
  >   , "format": "iso"
  >   , "type": "image"
  >   , "queued": "2013-04-16T11:23:45Z"
  >   }
  > , {
  >     "appliance": "/appliances/123"
  >   , "format": "xen"
  >   , "type": "image"
  >   , "queued": "2013-04-16T11:23:45Z"
  >   }
  > , {
  >     "appliance": "/appliances/123"
  >   , "format": "oem"
  >   , "type": "kiwi"
  >   , "queued": "2013-04-17T09:11:23Z"
  >   }
  > , {
  >     "appliance": "/appliances/123"
  >   , "format": "vmx"
  >   , "type": "kiwi"
  >   }
  > }

