.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

===================================
/appliances/:app/repositories/:name
===================================

.. contents::


Methods
*******


DELETE
++++++

Delete a repository from the appliance.

Example: ::

  < DELETE /appliances/123/repositories/openSUSE-12.3-oss

  > 204 No Content
