.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

==============================
/appliances/:app/gpg_keys/:key
==============================

.. contents::


Methods
*******

DELETE
++++++

Example: ::

  < DELETE /appliances/123/gpg_keys/testkey
  < Accept: $CT:result

  > 200 Ok
  > Content-Type: $CT:result

GET
+++

Example: ::

  < GET /appliances/123/gpg_keys/testkey
  < Accept: $CT:gpg-key

  > 200 Ok
  > Content-Type: $CT:gpg-key
  >
  > {
  >   "name": "testkey"
  > , "target": "rpm"
  > , "key": "-----BEGIN PGP PUBLIC KEY BLOCK-----..."
  > }

PUT
+++

Example: ::

  < PUT /appliances/123/gpg_keys/testkey
  < Content-Type: $CT:gpg-key
  <
  < {
  <   "name": "testkey"
  < , "target": "rpm"
  < , "key": "-----BEGIN PGP PUBLIC KEY BLOCK-----..."
  < }

  > 204 No Content

