.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

==============================
/admin/base-repositories/:base
==============================

.. contents::


Methods
*******

GET
+++

List base repositories for a base system.

Example: ::

  GET /admin/base-repositories/12.3

  200 Ok

  {
    "12.3": [
      {
        uri: "/admin/base-repositories/..."
      , name: "openSUSE 12.3 OSS"
      , url: "http://download.opensuse.org/distribution/12.3/repo/oss/"
      , enabled: true
      }
    , {
        uri: "/admin/base-repositories/..."
      , name: "openSUSE 12.3 non-OSS"
      , url: "http://download.opensuse.org/distribution/12.3/repo/non-oss/"
      , enabled: true
      }
    , {
        uri: "/admin/base-repositories/..."
      , name: "openSUSE 12.3 Updates"
      , url: "http://download.opensuse.org/update/12.3/"
      , enabled: true
      }
    ]
  }
