.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

===============
/amazons/queued
===============

.. contents::


Media Types
***********

See `Media Types`_.

.. _`Media Types`: ../../media-types.rest


Methods
*******

GET
+++

List queued uploads.

