.. vim: ft=rst sts=2 sw=2 tw=70
.. default-role:: literal

==================
/testdrives/:token
==================

.. contents::


Methods
*******

DELETE
++++++

Spec: ::

  Accept:
    $CT:result

  Status:
    200 Ok
  | 204 No Content
  Content-Type:
    &Accept

Example: ::

  < DELETE /testdrives/rAnDoM
  < Accept: $CT:result

  > 200 Ok
  > Content-Type: $CT:result

  > {
  >   "result": "ok"
  > }

GET
+++

Spec: ::

  Accept:
    $CT:testdrive

  Status:
    200 Ok
  Content-Type:
    &Accept

Example: ::

  < GET /testdrives/rAnDoM
  < Accept: $CT:testdrive

  > 200 Ok
  > Content-Type: $CT:testdrive
  >
  > {
  >   "build": "/appliances/123/4.5.6/oem"
  >   "url": "http://node77.susestudio.com/testdrive/start/O5QPQkNNab6DskxVUJWd?lang=en"
  >   "vnc": {
  >     "host": "node77.susestudio.com"
  >   , "port": 5900
  >   , "password": "AbRacADaBrA"
  >   }
  > }
